### PR TITLE
Fix bad console assignment

### LINKED ISSUE #161: IE8 has console error
I running multi-browser Javascript tests which catch console messages.
Only IE 8(and older) has Console Error:"'prototype' is null or not an object"

(Screenshots with BrowserStack Live)
image

Probably it comes from JSON3
https://github.com/bestiejs/json3/issues/86

### LINKED ISSUE #164: console.log in tests doesn't work on IE8 and lower
`console.log` in tests on IE8 and lower gives the following error -

```
Launching 1 worker(s) for 1 run(s).
[Windows XP, Internet Explorer 8.0] Failed: 1 tests, 0 passed, 1 failed; ran for 16ms
[Windows XP, Internet Explorer 8.0] Error: "Odd Tests: isOdd()" failed, Died on test #1 undefined: Object doesn't support this property or method
[Windows XP, Internet Explorer 8.0] Screenshot: https://s3.amazonaws.com/testautomation/f5d858132a3cb80355b16a6d6b337b7249dcc601/js-screenshot-1469619378.png
```

[Object doesn't support this property or method](https://s3.amazonaws.com/testautomation/f5d858132a3cb80355b16a6d6b337b7249dcc601/js-screenshot-1469619378.png)

Can reproduce this using `browserstack-runner` version >= 0.4.2

### LINKED ISSUE #212: 'console' is undefined with Qunit in IE 9
## Expected Behavior
QUnit test suite with 1 simple test passes successfully.

## Actual Behavior
QUnit test suite with 1 simple test fails with _global failure_ due to error `'console' is undefined (see screenshot).

## Steps to Reproduce the Problem

  1. single test suite `index.html`

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Test Suite</title>
		<link href="node_modules/qunitjs/qunit/qunit.css" rel="stylesheet">
		<script src="node_modules/qunitjs/qunit/qunit.js"></script>
		<script>
			QUnit.test('simple value', function (assert) {
				assert.expect(1);
				assert.strictEqual(true, true, 'testing...');
			});
		</script>
	</head>
	<body>
		<div id="qunit"></div>
		<div id="qunit-fixture"></div>
	</body>
</html>
```
  2. browserstack config:
```json
{
    "test_framework" : "qunit",
    "test_path": [
        "index.html"
    ],
    "exit_with_fail": true,
    "browsers": [
        "ie_9"
    ]
}
```

  3. Execute `node_modules/.bin/browserstack-runner`

## Platform details
 
  1. browserstack-runner version: `0.9.0`
  2. node version: v11.6.0
  3. os type and version: OSX Mojave 10.14.2

## Details

See screenshot:

screenshot 2019-01-02 at 19 22 54

The error points to: https://github.com/browserstack/browserstack-runner/blob/52b23f060a19c3a5d9d31db4b0cfa65334d926cc/lib/_patch/browserstack.js#L40

If I remember IE pecularities correctly this might be because you cannot do `var x = foo || ...` when `foo` has never been set up before, i.e. is very much indeed undefined. A test like `typeof foo == 'undefined'` might work better/be needed. This could be IE 6-8 knowledge though.

PS: also, the runner will just hang until it times out...

```
Launching 1 worker(s) for 1 run(s).
[Windows 7, Internet Explorer 9.0] Launching
[Windows 7, Internet Explorer 9.0] Received ack
[Windows 7, Internet Explorer 9.0] Launched
[Windows 7, Internet Explorer 9.0] Awaiting ack
```

### PR DESCRIPTION
**Pull request by Krinkle**
Follows-up 826d2c7c9edbc4.

Before that commit, the reason global "console" was globbered is that the
`var console` part of the inner `var console = {}` assignment was hosted by
the JavaScript engine. Thus the variable always existed in the local scope as
type "undefined", and so the conditional check never saw the real console, and
always created a custom one. Thus it always deleted the original console reference,
as well as any other it contained.

In commit 826d2c7c9edbc4, this was incorrectly fixed by assigning the unchecked
expression referring to `console`, thus no longer having a fallback to `{}` in older
browsers, because an unchecked reference like that throws an Uncaught ReferenceError.

As a result, browserstack-runner was unable to run in IE 9 or older.

Fixes https://github.com/browserstack/browserstack-runner/issues/161.
Fixes https://github.com/browserstack/browserstack-runner/issues/164.
Fixes https://github.com/browserstack/browserstack-runner/issues/212.

### CODE REVIEW

File: lib/_patch/browserstack.js [hunk 1]
```diff
@@ -37,7 +37,11 @@
     req.send(data);
   }
 
-  var browserstack_console = console || window.console || {};
+  // Change some console method to capture the logs.
+  // This must not replace the console object itself so that other console methods
+  //  from the browser or added by the tested application remain unaffected.
+  // https://github.com/browserstack/browserstack-runner/pull/199
+  var browserstack_console = window.console || {};
```
Comment (yashLadha) [inline lib/_patch/browserstack.js:44]: Can't we copy the prototype and update the concerned method only so that we do not lose over other methods as well as retain the current logic.

Comment (yashLadha) [reply lib/_patch/browserstack.js:44]: Isn't `console` and `window.console` in browser are same.
image

Comment (Krinkle) [reply lib/_patch/browserstack.js:44]: Yes, in JavaScript the global scope of variables is reflected into an object called `window` where each global variable is a property. There are some exceptions, but in general, yes, when a variable actually exists and is defined as global, then `foo === window.foo`.

The problem, and the reason this code exists, is with when the variable does not exist, such as in old Internet Explorer.

Try this one:

```js
window.thisdontexist
//> undefined
thisdontexist
//> Uncaught ReferenceError: thisdontexist is not defined
```

Previously this code used `console`. Which means that since the release of 826d2c7, browserstack-runner was completely broken in IE6-8, because after this `ReferenceError: console is not defined`, the program is terminated, the callback never installed, the worker unreachable, and the test results never arrive / timeout.

```js
var x = window.console || {};
// Modern browser > Console
// IE 6-8         > {}
```

```js
var x = console || {};
// Modern browser > Console
// IE 6-8         > Uncaught ReferenceError: console is not defined / Program terminated.
```

**Review by yashLadha — APPROVED** [review]

**Review by francisf — APPROVED** [review]
